content:
 - name: posts
   label: Posts
   path: content/posts
   type: collection
   fields:
    - name: title
      label: Title
      type: string
    - name: description
      label: Description
      type: string
    - name: date
      label: Date
      type: date