content:
  - name: posts
    label: Posts
    path: content/posts
    type: collection
    extension: mdx
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: date
        label: Date
        type: date
    view:
      fields: [title]
      primary: title
      sort: [date, title]
      default:
        search: ""
        sort: title
        order: desc
