content:
  - name: posts
    label: Posts
    path: content/posts
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: date
        label: Date
        type: date
      - name: body
        label: Body
        type: rich-text
        options:
          format: markdown
    view:
      fields: [title, date]
      primary: title
      sort: [date, title]
      default:
        search: ""
        sort: title
        order: desc

  - name: pages
    label: Pages
    path: content/pages
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: body
        label: Body
        type: rich-text
        options:
          format: markdown
    view:
      fields: [title]
      primary: title
      sort: [date, title]
      default:
        search: ""
        sort: title
        order: desc
